### PR TITLE
GitHub Action to automatically build and add dist files on PR

### PR DESCRIPTION
**Pull request by mmphego**
**This PR does the following:**
- Adds a [GitHub Action](https://docs.github.com/en/actions) that automatically builds and adds dist files when a PR is created.

**Motivation for the change**

There have been several incidents where developers forget to build and add dist files to the PR. This change ensures that developers do not need to build dist files manually.

### CODE REVIEW

**Comment by bngcebetsha** [comment]
Will this happen as soon as a PR is open and then continue happening for each commit after(less desirable) or will we have it happen after we have at least one approval(most desirable)?

**Comment by mmphego** [comment]
> I'm probably asking you to give me the world, but will this happen as soon as a PR is open and then continue happening for each commit after(less desirable) or will we have it happen after we have at least one approval(most desirable)?
> 
> Great feature BTW

Sadly, the way I mangled this Action; it'll run each time changes are pushed to the branch (which is not ideal). I will make changes such that it should only run when PR approval has been given. Thanks @bngcebetsha

**Comment by mmphego** [comment]
# Parked for now!
Investigating moving this to Jenkinsfile.

**Comment by kmadisa** [comment]
> > I'm probably asking you to give me the world, but will this happen as soon as a PR is open and then continue happening for each commit after(less desirable) or will we have it happen after we have at least one approval(most desirable)?
> > Great feature BTW
> 
> Sadly, the way I mangled this Action; it'll run each time changes are pushed to the branch (which is not ideal). I will make changes such that it should only run when PR approval has been given. Thanks @bngcebetsha

This might help, https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved.

**Review by amakhaba — APPROVED** [review]

**Comment by mmphego** [comment]
Closing PR as implementation is being done in the Jenkinsfile.

**Pull request closed without merging**
