### PR TITLE
Hotfix V25 - Display remaining time to next global sync

### PR DESCRIPTION
**Pull request by bngcebetsha**
This PR is the hotfix into V25 of the following changes:

- Display the minimum remaining time to the Next Global Sync on the subarray page.
  See merged PR on `master`: [524](https://github.com/ska-sa/katgui/pull/524)
  JIRA: [MT-1109](https://skaafrica.atlassian.net/browse/MT-1109)

- Fix the issue that occurs when running `developer mode` in the `console` tab, one can see the      following bug: `TypeError: Cannot read property '0' of undefined angular.js:15535`
  merged PR into `master` [526](https://github.com/ska-sa/katgui/pull/526)
  JIRA: [MT-1183](https://skaafrica.atlassian.net/browse/MT-1183)

See error on screenshot below
Screenshot 2020-01-09 at 09 23 45

### CODE REVIEW

**Comment by ofaletse** [comment]
It Looks Okay to me. However I am wondering what caused the `1 errored check`

**Comment by bngcebetsha** [comment]
> It Looks Okay to me, however I am wondering what caused the `1 errored check`

The?

**Comment by bngcebetsha** [comment]
> @bngcebetsha I am referring to: [link](http://ci.camlab.kat.ac.za/blue/organizations/jenkins/katgui-multibranch/detail/hotfix%2Fbngcebetsha%2FMT-1109%2Fdisplay-remaining-time-to-next-global-sync/3/pipeline).
> It might be related to jenkins issues, I have tested building the dist files and all is ok.

Oh I see,...let me build dust files and push. See if problem persists ...

**Comment by ajoubertza** [comment]
> @bngcebetsha I am referring to: [link](http://ci.camlab.kat.ac.za/blue/organizations/jenkins/katgui-multibranch/detail/hotfix%2Fbngcebetsha%2FMT-1109%2Fdisplay-remaining-time-to-next-global-sync/3/pipeline).
> It might be related to jenkins issues, I have tested building the dist files and all is ok.

The camguinode Docker label was disabled in Jenkins, so builds were not able to run.  I enabled it, but the image needs fixing - wrong version of node installed..

**Comment by ofaletse** [comment]
@ajoubertza Thanks for the information.

**Pull request merged**
