### PR TITLE
Update 'Search Discrete Sensors' box to do the search and retain current plot

### PR DESCRIPTION
**Pull request by bngcebetsha**
Update `SensorGraph` plot view to only filter sensor types for selection and not inherently change axes in the plotview.

- Sensorgraph control side window now provides both discrete and numeric sensors, consecutively, to the same plotting view.
- Switching between discrete and numeric sensors in the control side window does not alter/clear an existing plot.
- If the current plot contains sensors of a different type, then the plot will be cleared to draw the newly selected sensor.
- Numeric and discrete sensors are not yet plotted together

JIRA: [MT-2895](https://skaafrica.atlassian.net/browse/MT-2895)
FEATURE TICKET: [MKT-148](https://skaafrica.atlassian.net/browse/MKT-148)

Screenshot 2022-07-07 at 11 49 25
Screenshot 2022-07-07 at 11 49 39
Screenshot 2022-07-07 at 11 49 52
Screenshot 2022-07-07 at 11 50 03
Screenshot 2022-07-07 at 11 50 15

### CODE REVIEW

**Comment by rohanschwartz** [comment]
Please add the Jira link to the bottom of the PR description.

**Comment by rohanschwartz** [comment]
How do you test this? Is there a server running somewhere to test this? It would also help to have pictures in the PR description showing the changes.

**Comment by bngcebetsha** [comment]
> How do you test this? Is there a server running somewhere to test this? It would also help to have pictures in the PR description showing the changes.

@rohanschwartz the setup for katgui development is on the main README of the repo....you can run the branch from there and point your environment to site. Contact me or @mmphego for assistance if you need it :)

**Comment by rohanschwartz** [comment]
> @rohanschwartz the setup for katgui development is on the main README of the repo....you can run the branch from there and point your environment to site. Contact me or @mmphego for assistance if you need it :)

For frontend stuff, it would be nice to have a test setup that a reviewer can quickly test. For me to get my CAM system up and running will likely take a day. So the PR author deploys their branch to the test server before creating the PR, and then it's ready for the reviewer to quickly test. Just something to think about for the future.

**Comment by bngcebetsha** [comment]
> > @rohanschwartz the setup for katgui development is on the main README of the repo....you can run the branch from there and point your environment to site. Contact me or @mmphego for assistance if you need it :)
> 
> For frontend stuff, it would be nice to have a test setup that a reviewer can quickly test. For me to get my CAM system up and running will likely take a day. So the PR author deploys their branch to the test server before creating the PR, and then it's ready for the reviewer to quickly test. Just something to think about for the future.

Hi @rohanschwartz I agree with you, I managed to set things up here - http://portal.mkat.devkaroo.camlab.kat.ac.za/katgui/home

**Comment by rohanschwartz** [comment]
How do you see the version on KatGUI? I want to see the katversion which should show your GIT branch version.

**Comment by rohanschwartz** [comment]
- _Sensorgraph control side window now provides both discrete and numeric sensors, consecutively, to the same plotting view._
  - I understand that this is the end goal of this feature, and not fully implemented as yet in this story
- _Switching between discrete and numeric sensors in the control side window does not alter/clear an existing plot._
  - Tested and working
- _If the current plot contains sensors of a different type, then the plot will be cleared to draw the newly selected sensor._
  - This was as before, and still works
- _Numeric and discrete sensors are not yet plotted together_
  - Confirmed

**Review by rohanschwartz — APPROVED** [review]
With my limited knowledge of KATGUI, it looks good to me.

**Comment by mmphego** [comment]
@bngcebetsha PR #633 fixes the CI build errors. When approved please update your PR

**Review by mmphego — APPROVED** [review]
Logic looks good to me.

**Comment by bngcebetsha** [comment]
captured in  https://github.com/ska-sa/katgui/pull/634

**Pull request closed without merging**
