### PR TITLE
Hotfix V30: Update the rsc-aggregate-color for the receiver ready icon on katgui

### PR DESCRIPTION
**Pull request by bngcebetsha**
This hotfix PR, we update the `isReceiverReady()`  icon from `WARN`(yellow) to `ERROR`(red) when the receiver is NOT ready (aggregate has a value of false). The only difference between this and previous functionality is the color of the icon and what status it reflects.

#### Before
Screenshot 2022-01-19 at 15 29 47

#### After
Screenshot 2022-01-24 at 14 56 24

Screenshot 2022-01-24 at 14 55 49

JIRA: [MT-2843](https://skaafrica.atlassian.net/browse/MT-2843)

### CODE REVIEW

**Review by mmphego — APPROVED** [review]
LGTM!

**Comment by mmphego** [comment]
Please update the title to match the branch accordingly.

**Review by amakhaba — APPROVED** [review]
LGTM

**Comment by lanceWilliams** [comment]
where are the dist files?

**Review by lanceWilliams — APPROVED** [review]
The change itself looks ok, please don't forget the dist files.

**Pull request merged**
